### ISSUE TITLE
WebProtégé is not configured properly

### ISSUE THREAD

**Issue by JulJac** [protegeproject/protege-server#40] opened 2018-02-16 14:23 UTC
HI there, 

I'm new to protege and followed the instructions on (https://protegewiki.stanford.edu/wiki/WebProtege)
to set up protege on a newly installed VM-Ubuntu-server 16.04

I set up the 
data.directory=/data/webprotege  (chwon tomcat8)
and 
application.host=VMname:8080/webprotege-3.0.0
the DNS is pointing to the right IP and I can ping the VMname

When I open webprotege in InternetExplorer I only get the message "WebProégé is not configured properly"

I cant find any clue in a log file, nor is webprotege writing into the set log file /var/log/webprotege

I have ben tring arround for several hours now and cant figure it out.
could someone be so kind and point me into the right direction.

THANK you already!

**Comment by matthewhorridge** [comment] 2018-02-20 20:21
This issue should be filed over on the WebProtege repo.  In any case, it's a duplicate of [this issue](https://github.com/protegeproject/webprotege/issues/447).  Closing this here.

**Closed as completed by matthewhorridge** 2018-02-20 20:21 UTC
